### ISSUE TITLE
Cannot add new connections 

### ISSUE THREAD

**Issue by nvvalchev** [ArcadeAnalytics/arcadeanalytics-recipes#1]
Hello,

"arcade-standalone"  is currently unusable for two problems.

First: I could not add new datasource connections. Even when the test connection works, then when I hit the save button nothing is saved. When I try to remove the pre-existing DemoDB (OrientDB) connection I get the following error:
```
Referential integrity constraint violation: "FK_WIDGET_DATA_SOURCE_ID: PUBLIC.WIDGET FOREIGN KEY(DATA_SOURCE_ID) REFERENCES PUBLIC.DATA_SOURCE(ID) (110)"; SQL statement:
arcadeanalytics-single_1  | delete from data_source where id=? [23503-197]
```

Second: The connection check is another problem. I managed to get OK from test connection only for a CosmosDB instance, but not for Janus and OrientDB. E.g. for Janus I get the following error
```
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.TimeoutException: Timed out while waiting for an available host - check the client configuration and connectivity to the server if this message persists
arcadeanalytics-single_1  | 	at org.apache.tinkerpop.gremlin.driver.Client.submit(Client.java:225)
arcadeanalytics-single_1  | 	at org.apache.tinkerpop.gremlin.driver.Client.submit(Client.java:209)
arcadeanalytics-single_1  | 	at com.arcadeanalytics.provider.gremlin.GremlinDataProvider.testConnection(GremlinDataProvider.kt:278)
arcadeanalytics-single_1  | 	... 123 common frames omitted
```  
All the config is set as in the docs. What might be the problem?

**Comment by arcade-player** [comment]
You can't remove a data-source if a widget is using it. This is the first error.

for the second one, I guess you didn't start any database container. 
Referring the readme:

**NOTE: This compose does not containers with test databases, they are commented and not started"**

You need a running instance of one of the supported data store.

So, 
- run arcade
- run at least one od the datastore

**Comment by nvvalchev** [comment]
Thanks for the hint for the widget! After removing it, then I could remove also the OrientDB pre-defined connection.
 
However, I have still problem for adding a new connection. I've followed the documentation and tested with different DBs:
- CosmosDB - following https://arcadeanalytics.com/support-for-microsoft-cosmosdb/, I click "test connection" and get "connection is alive". However, when I click "save connection" the connection is not saved without any errors in the logs of arcadeanalytics.
- OrientDB 3 - following https://github.com/ArcadeAnalytics/arcadeanalytics-recipes#orientdb-30x-explore-the-demo-database, I have the same problem as above with CosmosDB - the connection test is ok, but it could not be saved.

**Comment by arcade-player** [comment]
Just tested. I'm able to create datasources without any issues. 
I created a datasource pointing to orientdb and another one using the Gremlin endpoint.
Note: orientdb should be up and working. If you use the provied compose, just point to localhost:2480 to access the orientDB studio web console.

Some questions:
-  do you have a rtunning instance of Cosmos? We don't provide it
- can you provide some logs?

**Comment by nvvalchev** [comment]
Yes, I have an running instance of CosmosDB. As described above with both CosmosDB and local OrientDB3 (provided in this repo and started with `docker-compose -f recipes/orientdb3.yml up`) I get OK on the connection test, but when I hit "save" there is nothing happening.
Here is the log of the arcade analytics process: 
[arcade.log](https://github.com/ArcadeAnalytics/arcadeanalytics-recipes/files/3744529/arcade.log)

**Comment by arcade-player** [comment]
I tested again with arcadeanalytics-standalone. After saving the new datasoure in the list of  available ones

Then. You can start to create  widgets using the new datasource.

In the image, the latest two are just created:

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/56138992/67159755-60943a80-f349-11e9-944a-9dd5242a9d11.png">

**Comment by nvvalchev** [comment]
Hi, I found the problem. I logged in as "user" with password "user", which seems to be able to create data sources, but strangely cannot see them (write-only behavior). Whereas, when logged-in with "admin", then I could both create and see data sources.
